In [6]:
import tensorflow as tf
import numpy as np

In [2]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
print(t.shape, t.dtype)

(2, 3) <dtype: 'float32'>


In [22]:
t[0, 0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [17]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [28]:
tf.math.log(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.       , 0.6931472, 1.0986123],
       [1.3862944, 1.609438 , 1.7917595]], dtype=float32)>